name: app_store_server_sdk
description: Apple App Store Server SDK for facilitating integrations with App Store Server API
homepage: https://github.com/Omnimind-Ltd/app-store-server-sdk
version: 1.1.7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.3.0
  http: ^0.13.4
  logging: ^1.0.2
  uuid: ^3.0.5
  jose: ^0.3.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
